version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
 ,
 "postCreateCommand": "echo '# Writing code upon codespace creation!'  >> codespace.md"